version: '3.6'
services:
  cloranc:
    image: willsofts/cloranc
    container_name: cloranc
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./config/default-docker.json:/usr/node/app/config/default.json
    ports:
      - 8080:8080
