sonar.host.url=http://localhost:9000
sonar.login=5c0b91db8a9e701b819eedd97b7c7085a47d519b
sonar.projectKey=CLORANC.js
sonar.projectName=CLORANC.js
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/assets/**,**/public/bootstrap*/**,**/public/cryptojs/**,**/public/fonts/**,**/public/img/**,**/public/pictures/**,**/public/jquery/**,**/public/js/socket.io.js,**/public/js/msal-*.js,**/public/tinymce/**,**/public/login/**,**/public/vft*/**,**/public/demo*/**,**/public/css/font-*.css
sonar.typescript.tsconfigPath=tsconfig.json

