sonar.host.url=http://localhost:9000
#sonar.login=5c0b91db8a9e701b819eedd97b7c7085a47d519b
sonar.login=squ_aef5d602e46e6b7bde8f594cb985c263a2ef9b3d
sonar.token=squ_aef5d602e46e6b7bde8f594cb985c263a2ef9b3d
sonar.projectKey=CLORANC.js
sonar.projectName=CLORANC.js
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/assets/**,**/public/bootstrap*/**,**/public/cryptojs/**,**/public/fonts/**,**/public/img/**,**/public/pictures/**,**/public/jquery/**,**/public/js/socket.io.js,**/public/js/msal-*.js,**/public/tinymce/**,**/public/login/**,**/public/chat/emoji/**,**/public/chat/js/**,**/public/chat/sounds/**,**/public/chat/chat.html,**/public/vft*/**,**/public/demo*/**,**/public/css/font-*.css
sonar.typescript.tsconfigPath=tsconfig.json

