sonar.host.url=http://localhost:9000
#sonar.login=6f2511049b81c5afd477964964d95baf5b2bf506
sonar.login=squ_aef5d602e46e6b7bde8f594cb985c263a2ef9b3d
sonar.token=squ_aef5d602e46e6b7bde8f594cb985c263a2ef9b3d
sonar.projectKey=ASSURE.js
sonar.projectName=ASSURE.js
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/assets/**,**/public/bootstrap*/**,**/public/cryptojs/**,**/public/fonts/**,**/public/img/**,**/public/pictures/**,**/public/jquery/**,**/public/js/socket.io.js,**/public/js/msal-*.js,**/public/tinymce/**,**/public/login/**,**/public/chat/emoji/**,**/public/chat/js/**,**/public/chat/sounds/**,**/public/chat/chat.html,**/public/vft*/**,**/public/demo*/**,**/public/exm*/**,**/public/css/font-*.css
sonar.typescript.tsconfigPath=tsconfig.json

